name: tag-to-zip

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Create-tag-to-zip: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Checkout-tag-and-zip
        run: |
          git fetch --tags
          git checkout ${{ github.event.inputs.tag }}
      - name: Upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: tex-trans-tool-${{ github.event.inputs.tag }}.zip
          path: ./*
