name: update-package-json-plas-tag

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  update-package-json: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: replace version
        run: |
         tempjson='mktemp'
         withoutvtagstr=`echo ${{ github.event.inputs.tag }} | sed -e "s/^v//"`
         URL="https://github.com/ReinaS-64892/TexTransTool/releases/download/${{ github.event.inputs.tag }}/tex-trans-tool-${{ github.event.inputs.tag }}.zip"
         jq ".version|=\"${withoutvtagstr}\" | .url|=\"${URL}\"" ./package.json > $tempjson
         mv $tempjson ./package.json
      - name: git commit
        run: |
          git config user.name  "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./package.json
          git commit -m "Update package.json"
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}
