name: update-version

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string

jobs:
  call-Update-Tag:
    uses: ./.github/workflows/UpdatePackageJsonPlasTag.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  call-TagToZip:
    needs: [call-Update-Tag]
    uses: ./.github/workflows/TagToZip.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  Create-Release-Draft-On-Tag:
    needs: [call-TagToZip]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: tex-trans-tool-${{ github.event.inputs.tag }}

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        ref: ${{ github.event.inputs.tag }}

    - uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.tag }}
        tag_name: ${{ github.event.inputs.tag }}
        draft: true
        files: |
          tex-trans-tool-${{ github.event.inputs.tag }}.zip
          TexTransTool/package.json
